export const MANAGED_BLOCK_START = "# >>> secret-protector begin";
export const MANAGED_BLOCK_END = "# <<< secret-protector end";

export const DEFAULT_POLICY: Record<string, unknown> = {
  version: 1,
  detection: {
    path_like_keys: [
      "path",
      "filepath",
      "file_path",
      "filename",
      "uri",
      "absolute_path",
      "absolutepath",
      "relative_path",
      "relativepath",
      "relative_workspace_path",
      "relativeworkspacepath",
    ],
    file_read_commands: [
      "cat",
      "head",
      "tail",
      "less",
      "more",
      "grep",
      "awk",
      "sed",
      "bat",
      "rg",
    ],
    default_mode: "block",
  },
  env: {
    block_exact: [
      "GITHUB_PAT",
      "OPENAI_API_KEY",
      "ANTHROPIC_API_KEY",
      "GEMINI_API_KEY",
      "AWS_ACCESS_KEY_ID",
      "AWS_SECRET_ACCESS_KEY",
      "AWS_SESSION_TOKEN",
      "AZURE_OPENAI_API_KEY",
      "SLACK_BOT_TOKEN",
      "NPM_TOKEN",
      "PYPI_TOKEN",
    ],
    block_regex: [
      "(?i)^[A-Z0-9_]*(TOKEN|SECRET|PASSWORD|PASS|API_KEY|PRIVATE_KEY|PAT)$",
    ],
    allow_exact: [
      "HOME",
      "PATH",
      "SHELL",
      "TERM",
      "USER",
      "LOGNAME",
      "PWD",
      "LANG",
      "TMPDIR",
      "TMP",
      "TEMP",
      "LC_ALL",
      "LC_CTYPE",
      "LC_MESSAGES",
    ],
    allow_regex: ["^LC_.*$"],
  },
  files: {
    block_globs: [
      ".env",
      ".env.*",
      "**/.env",
      "**/.env.*",
      "**/*.pem",
      "**/*.p12",
      "**/*.pfx",
      "**/*.key",
      "**/id_rsa",
      "**/id_rsa.*",
      "**/id_ed25519",
      "**/id_ed25519.*",
      "**/*secrets*.yml",
      "**/*secrets*.yaml",
      "**/*secrets*.json",
    ],
    block_regex: [
      "(?i)(^|/)(credentials?|secrets?|tokens?)(/|\\\\|$)",
      "(?i)(^|/)(\\.aws|\\.ssh|\\.gnupg)(/|$)",
    ],
    allow_globs: [
      ".env.example",
      ".env.template",
      ".env.sample",
      ".env.schema",
      "**/.env.example",
      "**/.env.template",
      "**/.env.sample",
      "**/.env.schema",
    ],
    allow_regex: [],
  },
  providers: {
    cursor: true,
    opencode: true,
    codex: true,
    copilot: true,
  },
  cursor: {
    events: {
      beforeSubmitPrompt: { enabled: true, mode: "block" },
      beforeReadFile: { enabled: true, mode: "block" },
      beforeTabFileRead: { enabled: true, mode: "block" },
      beforeShellExecution: { enabled: true, mode: "block" },
      preToolUse: { enabled: true, mode: "block" },
    },
  },
  opencode: {
    tool_execute_before: {
      mode: "block",
    },
  },
  copilot: {
    repo_file: ".github/copilot-content-exclusions.txt",
  },
  bypass_tags_enabled: true,
};
